apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-test
spec:
  template:
    spec:
      containers:
        - image: moredatta574/jenkins-demo 
          ports:
            - name: http1
              containerPort: 80
